/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desenvolvimento;

import java.awt.CardLayout;

/**
 *
 * @author FSOCIETY
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bntGroup1 = new javax.swing.ButtonGroup();
        bntGroup2 = new javax.swing.ButtonGroup();
        bntGroup3 = new javax.swing.ButtonGroup();
        bntGroup4 = new javax.swing.ButtonGroup();
        bntGroup5 = new javax.swing.ButtonGroup();
        bntGroup6 = new javax.swing.ButtonGroup();
        bntGroup7 = new javax.swing.ButtonGroup();
        bntGroup8 = new javax.swing.ButtonGroup();
        bntGroup9 = new javax.swing.ButtonGroup();
        bntGroup10 = new javax.swing.ButtonGroup();
        pnlPrincipal = new javax.swing.JPanel();
        pnlWelcome = new javax.swing.JPanel();
        btnStart = new javax.swing.JButton();
        lblWelcome = new javax.swing.JLabel();
        pnlQ1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtQ1 = new javax.swing.JTextArea();
        rbnQ102 = new javax.swing.JRadioButton();
        rbnQ103 = new javax.swing.JRadioButton();
        rbnQ104 = new javax.swing.JRadioButton();
        rbnQ101 = new javax.swing.JRadioButton();
        lblTitle01 = new javax.swing.JLabel();
        lblQ1 = new javax.swing.JLabel();
        pnlQ2 = new javax.swing.JPanel();
        lblTitle02 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtQ02 = new javax.swing.JTextArea();
        rbnQ105 = new javax.swing.JRadioButton();
        rbnQ106 = new javax.swing.JRadioButton();
        rbnQ107 = new javax.swing.JRadioButton();
        rbnQ108 = new javax.swing.JRadioButton();
        lblQ2 = new javax.swing.JLabel();
        pnlQ3 = new javax.swing.JPanel();
        rbnQ109 = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtQ3 = new javax.swing.JTextArea();
        lblTitle3 = new javax.swing.JLabel();
        rbnQ110 = new javax.swing.JRadioButton();
        rbnQ111 = new javax.swing.JRadioButton();
        rbnQ112 = new javax.swing.JRadioButton();
        lblQ3 = new javax.swing.JLabel();
        pnlQ4 = new javax.swing.JPanel();
        rbnQ113 = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtQ4 = new javax.swing.JTextArea();
        lblTitle4 = new javax.swing.JLabel();
        rbnQ114 = new javax.swing.JRadioButton();
        rbnQ115 = new javax.swing.JRadioButton();
        rbnQ116 = new javax.swing.JRadioButton();
        lblQ4 = new javax.swing.JLabel();
        pnlQ5 = new javax.swing.JPanel();
        rbnQ117 = new javax.swing.JRadioButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtQ5 = new javax.swing.JTextArea();
        lblTitle5 = new javax.swing.JLabel();
        rbnQ118 = new javax.swing.JRadioButton();
        rbnQ119 = new javax.swing.JRadioButton();
        rbnQ120 = new javax.swing.JRadioButton();
        lblQ5 = new javax.swing.JLabel();
        pnlQ6 = new javax.swing.JPanel();
        rbnQ121 = new javax.swing.JRadioButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtQ6 = new javax.swing.JTextArea();
        lblTitle6 = new javax.swing.JLabel();
        rbnQ122 = new javax.swing.JRadioButton();
        rbnQ123 = new javax.swing.JRadioButton();
        rbnQ124 = new javax.swing.JRadioButton();
        lblQ6 = new javax.swing.JLabel();
        pnlQ7 = new javax.swing.JPanel();
        rbnQ125 = new javax.swing.JRadioButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtQ7 = new javax.swing.JTextArea();
        lblTitle7 = new javax.swing.JLabel();
        rbnQ126 = new javax.swing.JRadioButton();
        rbnQ127 = new javax.swing.JRadioButton();
        rbnQ128 = new javax.swing.JRadioButton();
        lblQ7 = new javax.swing.JLabel();
        pnlQ8 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtQ8 = new javax.swing.JTextArea();
        lblTitle8 = new javax.swing.JLabel();
        rbnQ132 = new javax.swing.JRadioButton();
        rbnQ129 = new javax.swing.JRadioButton();
        rbnQ130 = new javax.swing.JRadioButton();
        rbnQ131 = new javax.swing.JRadioButton();
        lblQ8 = new javax.swing.JLabel();
        pnlQ9 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtQ9 = new javax.swing.JTextArea();
        lblTitle9 = new javax.swing.JLabel();
        rbnQ133 = new javax.swing.JRadioButton();
        rbnQ134 = new javax.swing.JRadioButton();
        rbnQ135 = new javax.swing.JRadioButton();
        rbnQ136 = new javax.swing.JRadioButton();
        lblQ9 = new javax.swing.JLabel();
        pnlQ10 = new javax.swing.JPanel();
        lblTitle10 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtQ10 = new javax.swing.JTextArea();
        rbnQ137 = new javax.swing.JRadioButton();
        rbnQ138 = new javax.swing.JRadioButton();
        rbnQ139 = new javax.swing.JRadioButton();
        rbnQ140 = new javax.swing.JRadioButton();
        lblQ10 = new javax.swing.JLabel();
        pnlResultado = new javax.swing.JPanel();
        lblResult = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblQ11 = new javax.swing.JLabel();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlPrincipal.setBackground(new java.awt.Color(255, 153, 51));
        pnlPrincipal.setName(""); // NOI18N
        pnlPrincipal.setLayout(new java.awt.CardLayout());

        pnlWelcome.setLayout(null);

        btnStart.setBackground(new java.awt.Color(255, 255, 255));
        btnStart.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnStart.setForeground(new java.awt.Color(0, 0, 255));
        btnStart.setText("START");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });
        pnlWelcome.add(btnStart);
        btnStart.setBounds(90, 400, 110, 31);

        lblWelcome.setIcon(new javax.swing.ImageIcon("C:\\Users\\FSOCIETY\\OneDrive\\Documents\\Courses\\System development technician\\Module 1\\Técnicas de programação\\November\\25-11-20\\Welcome.png")); // NOI18N
        pnlWelcome.add(lblWelcome);
        lblWelcome.setBounds(0, 0, 300, 533);

        pnlPrincipal.add(pnlWelcome, "Welcome");

        pnlQ1.setBackground(new java.awt.Color(255, 255, 255));
        pnlQ1.setLayout(null);

        txtQ1.setColumns(20);
        txtQ1.setForeground(new java.awt.Color(255, 0, 0));
        txtQ1.setRows(5);
        txtQ1.setText("\n\n QUEM FUNDOU A MICROSOFT?\n");
        txtQ1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtQ1.setCaretColor(new java.awt.Color(255, 255, 255));
        txtQ1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(txtQ1);

        pnlQ1.add(jScrollPane2);
        jScrollPane2.setBounds(50, 70, 200, 113);

        rbnQ102.setBackground(new java.awt.Color(163, 157, 198));
        bntGroup1.add(rbnQ102);
        rbnQ102.setText("Bil Gates e Paul Allen");
        rbnQ102.setToolTipText("");
        rbnQ102.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnQ102ActionPerformed(evt);
            }
        });
        pnlQ1.add(rbnQ102);
        rbnQ102.setBounds(50, 320, 200, 23);

        rbnQ103.setBackground(new java.awt.Color(163, 157, 198));
        bntGroup1.add(rbnQ103);
        rbnQ103.setText("Mark Zuckerberg ");
        rbnQ103.setToolTipText("");
        rbnQ103.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnQ103ActionPerformed(evt);
            }
        });
        pnlQ1.add(rbnQ103);
        rbnQ103.setBounds(50, 380, 200, 23);

        rbnQ104.setBackground(new java.awt.Color(163, 157, 198));
        bntGroup1.add(rbnQ104);
        rbnQ104.setText("James Gosling");
        rbnQ104.setToolTipText("");
        rbnQ104.setActionCommand("James Gosling e Bill Joy");
        rbnQ104.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnQ104ActionPerformed(evt);
            }
        });
        pnlQ1.add(rbnQ104);
        rbnQ104.setBounds(50, 440, 200, 23);

        rbnQ101.setBackground(new java.awt.Color(163, 157, 198));
        bntGroup1.add(rbnQ101);
        rbnQ101.setText("Steve Jobs e Steve Wozniak ");
        rbnQ101.setToolTipText("");
        rbnQ101.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnQ101ActionPerformed(evt);
            }
        });
        pnlQ1.add(rbnQ101);
        rbnQ101.setBounds(50, 250, 200, 23);

        lblTitle01.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTitle01.setText("Question - 01");
        pnlQ1.add(lblTitle01);
        lblTitle01.setBounds(100, 30, 190, 30);

        lblQ1.setIcon(new javax.swing.ImageIcon("C:\\Users\\FSOCIETY\\OneDrive\\Documents\\Courses\\System development technician\\Module 1\\Técnicas de programação\\November\\25-11-20\\QuizQuestions.png")); // NOI18N
        pnlQ1.add(lblQ1);
        lblQ1.setBounds(0, 0, 300, 533);

        pnlPrincipal.add(pnlQ1, "Q1");

        pnlQ2.setBackground(new java.awt.Color(255, 255, 255));
        pnlQ2.setLayout(null);

        lblTitle02.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTitle02.setText("Question - 02");
        pnlQ2.add(lblTitle02);
        lblTitle02.setBounds(100, 30, 190, 30);

        txtQ02.setColumns(20);
        txtQ02.setForeground(new java.awt.Color(255, 0, 0));
        txtQ02.setRows(5);
        txtQ02.setText("QUAL O NOME DO PRIMEIRO\nCOMPUTADOR DO MUNDO ?\n");
        txtQ02.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtQ02.setCaretColor(new java.awt.Color(255, 255, 255));
        txtQ02.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(txtQ02);

        pnlQ2.add(jScrollPane1);
        jScrollPane1.setBounds(50, 80, 200, 113);

        rbnQ105.setBackground(new java.awt.Color(163, 157, 198));
        bntGroup2.add(rbnQ105);
        rbnQ105.setText("ALIENWARE");
        rbnQ105.setToolTipText("");
        rbnQ105.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnQ105ActionPerformed(evt);
            }
        });
        pnlQ2.add(rbnQ105);
        rbnQ105.setBounds(50, 250, 200, 23);

        rbnQ106.setBackground(new java.awt.Color(163, 157, 198));
        bntGroup2.add(rbnQ106);
        rbnQ106.setText("APPLE I");
        rbnQ106.setToolTipText("");
        rbnQ106.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnQ106ActionPerformed(evt);
            }
        });
        pnlQ2.add(rbnQ106);
        rbnQ106.setBounds(50, 380, 200, 23);

        rbnQ107.setBackground(new java.awt.Color(163, 157, 198));
        bntGroup2.add(rbnQ107);
        rbnQ107.setText("ENIAC");
        rbnQ107.setToolTipText("");
        rbnQ107.setActionCommand("James Gosling e Bill Joy");
        rbnQ107.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnQ107ActionPerformed(evt);
            }
        });
        pnlQ2.add(rbnQ107);
        rbnQ107.setBounds(50, 440, 200, 23);

        rbnQ108.setBackground(new java.awt.Color(163, 157, 198));
        bntGroup2.add(rbnQ108);
        rbnQ108.setText("IBM 702");
        rbnQ108.setToolTipText("");
        rbnQ108.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnQ108ActionPerformed(evt);
            }
        });
        pnlQ2.add(rbnQ108);
        rbnQ108.setBounds(50, 320, 200, 23);

        lblQ2.setIcon(new javax.swing.ImageIcon("C:\\Users\\FSOCIETY\\OneDrive\\Documents\\Courses\\System development technician\\Module 1\\Técnicas de programação\\November\\25-11-20\\QuizQuestions.png")); // NOI18N
        pnlQ2.add(lblQ2);
        lblQ2.setBounds(0, 0, 300, 533);

        pnlPrincipal.add(pnlQ2, "Q2");

        pnlQ3.setBackground(new java.awt.Color(255, 255, 255));
        pnlQ3.setLayout(null);

        rbnQ109.setBackground(new java.awt.Color(163, 157, 198));
        bntGroup3.add(rbnQ109);
        rbnQ109.setText("Hypertext Markup Language");
        rbnQ109.setToolTipText("");
        rbnQ109.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnQ109ActionPerformed(evt);
            }
        });
        pnlQ3.add(rbnQ109);
        rbnQ109.setBounds(50, 250, 200, 23);

        txtQ3.setColumns(20);
        txtQ3.setForeground(new java.awt.Color(255, 0, 0));
        txtQ3.setRows(5);
        txtQ3.setText("O QUE SIGNIFICA A SIGLA\nHTML?\n");
        txtQ3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtQ3.setCaretColor(new java.awt.Color(255, 255, 255));
        txtQ3.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(txtQ3);

        pnlQ3.add(jScrollPane3);
        jScrollPane3.setBounds(50, 80, 200, 113);

        lblTitle3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTitle3.setText("Question - 03");
        pnlQ3.add(lblTitle3);
        lblTitle3.setBounds(100, 30, 190, 30);

        rbnQ110.setBackground(new java.awt.Color(163, 157, 198));
        bntGroup3.add(rbnQ110);
        rbnQ110.setText("Nada");
        rbnQ110.setToolTipText("");
        rbnQ110.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnQ110ActionPerformed(evt);
            }
        });
        pnlQ3.add(rbnQ110);
        rbnQ110.setBounds(50, 380, 200, 23);

        rbnQ111.setBackground(new java.awt.Color(163, 157, 198));
        bntGroup3.add(rbnQ111);
        rbnQ111.setText("Huge True Maze Legendary");
        rbnQ111.setToolTipText("");
        rbnQ111.setActionCommand("James Gosling e Bill Joy");
        rbnQ111.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnQ111ActionPerformed(evt);
            }
        });
        pnlQ3.add(rbnQ111);
        rbnQ111.setBounds(50, 440, 200, 23);

        rbnQ112.setBackground(new java.awt.Color(163, 157, 198));
        bntGroup3.add(rbnQ112);
        rbnQ112.setText("eXtensible Markup Language");
        rbnQ112.setToolTipText("");
        rbnQ112.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnQ112ActionPerformed(evt);
            }
        });
        pnlQ3.add(rbnQ112);
        rbnQ112.setBounds(50, 320, 200, 23);

        lblQ3.setIcon(new javax.swing.ImageIcon("C:\\Users\\FSOCIETY\\OneDrive\\Documents\\Courses\\System development technician\\Module 1\\Técnicas de programação\\November\\25-11-20\\QuizQuestions.png")); // NOI18N
        pnlQ3.add(lblQ3);
        lblQ3.setBounds(0, 0, 300, 533);

        pnlPrincipal.add(pnlQ3, "Q3");

        pnlQ4.setBackground(new java.awt.Color(255, 255, 255));
        pnlQ4.setLayout(null);

        rbnQ113.setBackground(new java.awt.Color(163, 157, 198));
        bntGroup4.add(rbnQ113);
        rbnQ113.setText("Personal Computer");
        rbnQ113.setToolTipText("");
        rbnQ113.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnQ113ActionPerformed(evt);
            }
        });
        pnlQ4.add(rbnQ113);
        rbnQ113.setBounds(50, 250, 200, 23);

        txtQ4.setColumns(20);
        txtQ4.setForeground(new java.awt.Color(255, 0, 0));
        txtQ4.setRows(5);
        txtQ4.setText("NA COMPUTAÇÃO O QUE\nSIGNIFICA A SIGLA PC?\n");
        txtQ4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtQ4.setCaretColor(new java.awt.Color(255, 255, 255));
        txtQ4.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane4.setViewportView(txtQ4);

        pnlQ4.add(jScrollPane4);
        jScrollPane4.setBounds(50, 80, 200, 113);

        lblTitle4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTitle4.setText("Question - 04");
        pnlQ4.add(lblTitle4);
        lblTitle4.setBounds(100, 30, 190, 30);

        rbnQ114.setBackground(new java.awt.Color(163, 157, 198));
        bntGroup4.add(rbnQ114);
        rbnQ114.setText("Paulo Cesar");
        rbnQ114.setToolTipText("");
        rbnQ114.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnQ114ActionPerformed(evt);
            }
        });
        pnlQ4.add(rbnQ114);
        rbnQ114.setBounds(50, 380, 200, 23);

        rbnQ115.setBackground(new java.awt.Color(163, 157, 198));
        bntGroup4.add(rbnQ115);
        rbnQ115.setText("Protocol Control");
        rbnQ115.setToolTipText("");
        rbnQ115.setActionCommand("James Gosling e Bill Joy");
        rbnQ115.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnQ115ActionPerformed(evt);
            }
        });
        pnlQ4.add(rbnQ115);
        rbnQ115.setBounds(50, 440, 200, 23);

        rbnQ116.setBackground(new java.awt.Color(163, 157, 198));
        bntGroup4.add(rbnQ116);
        rbnQ116.setText("Personal Creation");
        rbnQ116.setToolTipText("");
        rbnQ116.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnQ116ActionPerformed(evt);
            }
        });
        pnlQ4.add(rbnQ116);
        rbnQ116.setBounds(50, 320, 200, 23);

        lblQ4.setIcon(new javax.swing.ImageIcon("C:\\Users\\FSOCIETY\\OneDrive\\Documents\\Courses\\System development technician\\Module 1\\Técnicas de programação\\November\\25-11-20\\QuizQuestions.png")); // NOI18N
        pnlQ4.add(lblQ4);
        lblQ4.setBounds(0, 0, 300, 533);

        pnlPrincipal.add(pnlQ4, "Q4");

        pnlQ5.setBackground(new java.awt.Color(255, 255, 255));
        pnlQ5.setLayout(null);

        rbnQ117.setBackground(new java.awt.Color(163, 157, 198));
        bntGroup5.add(rbnQ117);
        rbnQ117.setText("13");
        rbnQ117.setToolTipText("");
        rbnQ117.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnQ117ActionPerformed(evt);
            }
        });
        pnlQ5.add(rbnQ117);
        rbnQ117.setBounds(50, 250, 200, 23);

        txtQ5.setColumns(20);
        txtQ5.setForeground(new java.awt.Color(255, 0, 0));
        txtQ5.setRows(5);
        txtQ5.setText("1010 no sistema binário\né equivalente a qual \nnúmero no sistema \ndecimal? ");
        txtQ5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtQ5.setCaretColor(new java.awt.Color(255, 255, 255));
        txtQ5.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane5.setViewportView(txtQ5);

        pnlQ5.add(jScrollPane5);
        jScrollPane5.setBounds(50, 80, 200, 113);

        lblTitle5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTitle5.setText("Question - 05");
        pnlQ5.add(lblTitle5);
        lblTitle5.setBounds(100, 30, 190, 30);

        rbnQ118.setBackground(new java.awt.Color(163, 157, 198));
        bntGroup5.add(rbnQ118);
        rbnQ118.setText("9");
        rbnQ118.setToolTipText("");
        rbnQ118.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnQ118ActionPerformed(evt);
            }
        });
        pnlQ5.add(rbnQ118);
        rbnQ118.setBounds(50, 380, 200, 23);

        rbnQ119.setBackground(new java.awt.Color(163, 157, 198));
        bntGroup5.add(rbnQ119);
        rbnQ119.setText("14");
        rbnQ119.setToolTipText("");
        rbnQ119.setActionCommand("James Gosling e Bill Joy");
        rbnQ119.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnQ119ActionPerformed(evt);
            }
        });
        pnlQ5.add(rbnQ119);
        rbnQ119.setBounds(50, 440, 200, 23);

        rbnQ120.setBackground(new java.awt.Color(163, 157, 198));
        bntGroup5.add(rbnQ120);
        rbnQ120.setText("10");
        rbnQ120.setToolTipText("");
        rbnQ120.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnQ120ActionPerformed(evt);
            }
        });
        pnlQ5.add(rbnQ120);
        rbnQ120.setBounds(50, 320, 200, 23);

        lblQ5.setIcon(new javax.swing.ImageIcon("C:\\Users\\FSOCIETY\\OneDrive\\Documents\\Courses\\System development technician\\Module 1\\Técnicas de programação\\November\\25-11-20\\QuizQuestions.png")); // NOI18N
        pnlQ5.add(lblQ5);
        lblQ5.setBounds(0, 0, 300, 533);

        pnlPrincipal.add(pnlQ5, "Q5");

        pnlQ6.setBackground(new java.awt.Color(255, 255, 255));
        pnlQ6.setLayout(null);

        rbnQ121.setBackground(new java.awt.Color(163, 157, 198));
        bntGroup6.add(rbnQ121);
        rbnQ121.setText("Programa");
        rbnQ121.setToolTipText("");
        rbnQ121.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnQ121ActionPerformed(evt);
            }
        });
        pnlQ6.add(rbnQ121);
        rbnQ121.setBounds(50, 250, 200, 23);

        txtQ6.setColumns(20);
        txtQ6.setForeground(new java.awt.Color(255, 0, 0));
        txtQ6.setRows(5);
        txtQ6.setText("\n  \n   O que é o MS-DOS? ");
        txtQ6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtQ6.setCaretColor(new java.awt.Color(255, 255, 255));
        txtQ6.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane6.setViewportView(txtQ6);

        pnlQ6.add(jScrollPane6);
        jScrollPane6.setBounds(50, 80, 200, 113);

        lblTitle6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTitle6.setText("Question - 06");
        pnlQ6.add(lblTitle6);
        lblTitle6.setBounds(100, 30, 190, 30);

        rbnQ122.setBackground(new java.awt.Color(163, 157, 198));
        bntGroup6.add(rbnQ122);
        rbnQ122.setText("Sistema Operacional");
        rbnQ122.setToolTipText("");
        rbnQ122.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnQ122ActionPerformed(evt);
            }
        });
        pnlQ6.add(rbnQ122);
        rbnQ122.setBounds(50, 380, 200, 23);

        rbnQ123.setBackground(new java.awt.Color(163, 157, 198));
        bntGroup6.add(rbnQ123);
        rbnQ123.setText("Linguagem de Programação");
        rbnQ123.setToolTipText("");
        rbnQ123.setActionCommand("James Gosling e Bill Joy");
        rbnQ123.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnQ123ActionPerformed(evt);
            }
        });
        pnlQ6.add(rbnQ123);
        rbnQ123.setBounds(50, 440, 200, 23);

        rbnQ124.setBackground(new java.awt.Color(163, 157, 198));
        bntGroup6.add(rbnQ124);
        rbnQ124.setText("Vírus de computador");
        rbnQ124.setToolTipText("");
        rbnQ124.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnQ124ActionPerformed(evt);
            }
        });
        pnlQ6.add(rbnQ124);
        rbnQ124.setBounds(50, 320, 200, 23);

        lblQ6.setIcon(new javax.swing.ImageIcon("C:\\Users\\FSOCIETY\\OneDrive\\Documents\\Courses\\System development technician\\Module 1\\Técnicas de programação\\November\\25-11-20\\QuizQuestions.png")); // NOI18N
        pnlQ6.add(lblQ6);
        lblQ6.setBounds(0, 0, 300, 533);

        pnlPrincipal.add(pnlQ6, "Q6");

        pnlQ7.setBackground(new java.awt.Color(255, 255, 255));
        pnlQ7.setLayout(null);

        rbnQ125.setBackground(new java.awt.Color(163, 157, 198));
        bntGroup7.add(rbnQ125);
        rbnQ125.setText("Random Access Memory");
        rbnQ125.setToolTipText("");
        rbnQ125.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnQ125ActionPerformed(evt);
            }
        });
        pnlQ7.add(rbnQ125);
        rbnQ125.setBounds(50, 250, 200, 23);

        txtQ7.setColumns(20);
        txtQ7.setForeground(new java.awt.Color(255, 0, 0));
        txtQ7.setRows(5);
        txtQ7.setText("      \n   O que significa          \n    memória RAM?");
        txtQ7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtQ7.setCaretColor(new java.awt.Color(255, 255, 255));
        txtQ7.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane7.setViewportView(txtQ7);

        pnlQ7.add(jScrollPane7);
        jScrollPane7.setBounds(50, 80, 200, 113);

        lblTitle7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTitle7.setText("Question - 07");
        pnlQ7.add(lblTitle7);
        lblTitle7.setBounds(100, 30, 190, 30);

        rbnQ126.setBackground(new java.awt.Color(163, 157, 198));
        bntGroup7.add(rbnQ126);
        rbnQ126.setText("Hard Disk");
        rbnQ126.setToolTipText("");
        rbnQ126.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnQ126ActionPerformed(evt);
            }
        });
        pnlQ7.add(rbnQ126);
        rbnQ126.setBounds(50, 380, 200, 23);

        rbnQ127.setBackground(new java.awt.Color(163, 157, 198));
        bntGroup7.add(rbnQ127);
        rbnQ127.setText("Frog Memory");
        rbnQ127.setToolTipText("");
        rbnQ127.setActionCommand("James Gosling e Bill Joy");
        rbnQ127.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnQ127ActionPerformed(evt);
            }
        });
        pnlQ7.add(rbnQ127);
        rbnQ127.setBounds(50, 440, 200, 23);

        rbnQ128.setBackground(new java.awt.Color(163, 157, 198));
        bntGroup7.add(rbnQ128);
        rbnQ128.setText("Read Only Memory");
        rbnQ128.setToolTipText("");
        rbnQ128.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnQ128ActionPerformed(evt);
            }
        });
        pnlQ7.add(rbnQ128);
        rbnQ128.setBounds(50, 320, 200, 23);

        lblQ7.setIcon(new javax.swing.ImageIcon("C:\\Users\\FSOCIETY\\OneDrive\\Documents\\Courses\\System development technician\\Module 1\\Técnicas de programação\\November\\25-11-20\\QuizQuestions.png")); // NOI18N
        pnlQ7.add(lblQ7);
        lblQ7.setBounds(0, 0, 300, 533);

        pnlPrincipal.add(pnlQ7, "Q7");

        pnlQ8.setBackground(new java.awt.Color(255, 255, 255));
        pnlQ8.setLayout(null);

        txtQ8.setColumns(20);
        txtQ8.setForeground(new java.awt.Color(255, 0, 0));
        txtQ8.setRows(5);
        txtQ8.setText("      \n   O que é um C.I? ");
        txtQ8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtQ8.setCaretColor(new java.awt.Color(255, 255, 255));
        txtQ8.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane8.setViewportView(txtQ8);

        pnlQ8.add(jScrollPane8);
        jScrollPane8.setBounds(50, 80, 200, 96);

        lblTitle8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTitle8.setText("Question - 08");
        pnlQ8.add(lblTitle8);
        lblTitle8.setBounds(100, 30, 190, 30);

        rbnQ132.setBackground(new java.awt.Color(163, 157, 198));
        bntGroup8.add(rbnQ132);
        rbnQ132.setText("Collateral Information");
        rbnQ132.setToolTipText("");
        rbnQ132.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnQ132ActionPerformed(evt);
            }
        });
        pnlQ8.add(rbnQ132);
        rbnQ132.setBounds(50, 320, 200, 23);

        rbnQ129.setBackground(new java.awt.Color(163, 157, 198));
        bntGroup8.add(rbnQ129);
        rbnQ129.setText("Circuito Integrado");
        rbnQ129.setToolTipText("");
        rbnQ129.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnQ129ActionPerformed(evt);
            }
        });
        pnlQ8.add(rbnQ129);
        rbnQ129.setBounds(50, 380, 200, 23);

        rbnQ130.setBackground(new java.awt.Color(163, 157, 198));
        bntGroup8.add(rbnQ130);
        rbnQ130.setText("Censure International");
        rbnQ130.setToolTipText("");
        rbnQ130.setActionCommand("James Gosling e Bill Joy");
        rbnQ130.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnQ130ActionPerformed(evt);
            }
        });
        pnlQ8.add(rbnQ130);
        rbnQ130.setBounds(50, 440, 200, 23);

        rbnQ131.setBackground(new java.awt.Color(163, 157, 198));
        bntGroup8.add(rbnQ131);
        rbnQ131.setText("Calibrated instrument");
        rbnQ131.setToolTipText("");
        rbnQ131.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnQ131ActionPerformed(evt);
            }
        });
        pnlQ8.add(rbnQ131);
        rbnQ131.setBounds(50, 260, 200, 23);

        lblQ8.setIcon(new javax.swing.ImageIcon("C:\\Users\\FSOCIETY\\OneDrive\\Documents\\Courses\\System development technician\\Module 1\\Técnicas de programação\\November\\25-11-20\\QuizQuestions.png")); // NOI18N
        pnlQ8.add(lblQ8);
        lblQ8.setBounds(0, 0, 300, 533);

        pnlPrincipal.add(pnlQ8, "Q8");

        pnlQ9.setBackground(new java.awt.Color(255, 255, 255));
        pnlQ9.setLayout(null);

        txtQ9.setColumns(20);
        txtQ9.setForeground(new java.awt.Color(255, 0, 0));
        txtQ9.setRows(5);
        txtQ9.setText("      \n   1024 bytes é \n   equivalente ...  ");
        txtQ9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtQ9.setCaretColor(new java.awt.Color(255, 255, 255));
        txtQ9.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane9.setViewportView(txtQ9);

        pnlQ9.add(jScrollPane9);
        jScrollPane9.setBounds(50, 80, 200, 96);

        lblTitle9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTitle9.setText("Question - 09");
        pnlQ9.add(lblTitle9);
        lblTitle9.setBounds(100, 30, 190, 30);

        rbnQ133.setBackground(new java.awt.Color(163, 157, 198));
        bntGroup9.add(rbnQ133);
        rbnQ133.setText("1 Terabyte");
        rbnQ133.setToolTipText("");
        rbnQ133.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnQ133ActionPerformed(evt);
            }
        });
        pnlQ9.add(rbnQ133);
        rbnQ133.setBounds(50, 320, 200, 23);

        rbnQ134.setBackground(new java.awt.Color(163, 157, 198));
        bntGroup9.add(rbnQ134);
        rbnQ134.setText("10 Megabytes");
        rbnQ134.setToolTipText("");
        rbnQ134.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnQ134ActionPerformed(evt);
            }
        });
        pnlQ9.add(rbnQ134);
        rbnQ134.setBounds(50, 380, 200, 23);

        rbnQ135.setBackground(new java.awt.Color(163, 157, 198));
        bntGroup9.add(rbnQ135);
        rbnQ135.setText("1 Kilobyte");
        rbnQ135.setToolTipText("");
        rbnQ135.setActionCommand("James Gosling e Bill Joy");
        rbnQ135.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnQ135ActionPerformed(evt);
            }
        });
        pnlQ9.add(rbnQ135);
        rbnQ135.setBounds(50, 440, 200, 23);

        rbnQ136.setBackground(new java.awt.Color(163, 157, 198));
        bntGroup9.add(rbnQ136);
        rbnQ136.setText("1 byte");
        rbnQ136.setToolTipText("");
        rbnQ136.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnQ136ActionPerformed(evt);
            }
        });
        pnlQ9.add(rbnQ136);
        rbnQ136.setBounds(50, 260, 200, 23);

        lblQ9.setIcon(new javax.swing.ImageIcon("C:\\Users\\FSOCIETY\\OneDrive\\Documents\\Courses\\System development technician\\Module 1\\Técnicas de programação\\November\\25-11-20\\QuizQuestions.png")); // NOI18N
        pnlQ9.add(lblQ9);
        lblQ9.setBounds(0, 0, 300, 533);

        pnlPrincipal.add(pnlQ9, "Q9");

        pnlQ10.setBackground(new java.awt.Color(255, 255, 255));
        pnlQ10.setLayout(null);

        lblTitle10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lblTitle10.setText("Question - 10");
        pnlQ10.add(lblTitle10);
        lblTitle10.setBounds(100, 30, 190, 30);

        txtQ10.setColumns(20);
        txtQ10.setForeground(new java.awt.Color(255, 0, 0));
        txtQ10.setRows(5);
        txtQ10.setText("      \n  Oque significa SSD?  ");
        txtQ10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtQ10.setCaretColor(new java.awt.Color(255, 255, 255));
        txtQ10.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jScrollPane10.setViewportView(txtQ10);

        pnlQ10.add(jScrollPane10);
        jScrollPane10.setBounds(50, 80, 200, 113);

        rbnQ137.setBackground(new java.awt.Color(163, 157, 198));
        bntGroup10.add(rbnQ137);
        rbnQ137.setText("Solid State Drives");
        rbnQ137.setToolTipText("");
        rbnQ137.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnQ137ActionPerformed(evt);
            }
        });
        pnlQ10.add(rbnQ137);
        rbnQ137.setBounds(50, 320, 200, 23);

        rbnQ138.setBackground(new java.awt.Color(163, 157, 198));
        bntGroup10.add(rbnQ138);
        rbnQ138.setText("Scuffle Shirk Debrief ");
        rbnQ138.setToolTipText("");
        rbnQ138.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnQ138ActionPerformed(evt);
            }
        });
        pnlQ10.add(rbnQ138);
        rbnQ138.setBounds(50, 380, 200, 23);

        rbnQ139.setBackground(new java.awt.Color(163, 157, 198));
        bntGroup10.add(rbnQ139);
        rbnQ139.setText("Superficial Surreal Definition");
        rbnQ139.setToolTipText("");
        rbnQ139.setActionCommand("James Gosling e Bill Joy");
        rbnQ139.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnQ139ActionPerformed(evt);
            }
        });
        pnlQ10.add(rbnQ139);
        rbnQ139.setBounds(50, 440, 200, 23);

        rbnQ140.setBackground(new java.awt.Color(163, 157, 198));
        bntGroup10.add(rbnQ140);
        rbnQ140.setText("Seldom Sabotage Decisive");
        rbnQ140.setToolTipText("");
        rbnQ140.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnQ140ActionPerformed(evt);
            }
        });
        pnlQ10.add(rbnQ140);
        rbnQ140.setBounds(50, 260, 200, 23);

        lblQ10.setIcon(new javax.swing.ImageIcon("C:\\Users\\FSOCIETY\\OneDrive\\Documents\\Courses\\System development technician\\Module 1\\Técnicas de programação\\November\\25-11-20\\QuizQuestions.png")); // NOI18N
        pnlQ10.add(lblQ10);
        lblQ10.setBounds(0, 0, 300, 533);

        pnlPrincipal.add(pnlQ10, "Q10");

        pnlResultado.setBackground(new java.awt.Color(255, 255, 255));
        pnlResultado.setLayout(null);

        lblResult.setBackground(new java.awt.Color(0, 0, 0));
        lblResult.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblResult.setText("...");
        pnlResultado.add(lblResult);
        lblResult.setBounds(110, 260, 116, 43);

        jButton1.setText("CALCULAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnlResultado.add(jButton1);
        jButton1.setBounds(100, 410, 110, 30);

        lblQ11.setIcon(new javax.swing.ImageIcon("C:\\Users\\FSOCIETY\\OneDrive\\Documents\\Courses\\System development technician\\Module 1\\Técnicas de programação\\November\\25-11-20\\Score.png")); // NOI18N
        pnlResultado.add(lblQ11);
        lblQ11.setBounds(0, 0, 310, 533);

        pnlPrincipal.add(pnlResultado, "Result");

        btnPrevious.setText("Previous");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
CardLayout cartao = (CardLayout)pnlPrincipal.getLayout();
cartao.show(pnlPrincipal,"Q1");
        // TODO add your handling code here:
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
CardLayout cartao = (CardLayout)pnlPrincipal.getLayout();
cartao.previous(pnlPrincipal);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
CardLayout cartao = (CardLayout)pnlPrincipal.getLayout();
cartao.next(pnlPrincipal);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNextActionPerformed

    private void rbnQ101ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnQ101ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnQ101ActionPerformed

    private void rbnQ102ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnQ102ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnQ102ActionPerformed

    private void rbnQ103ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnQ103ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnQ103ActionPerformed

    private void rbnQ104ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnQ104ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnQ104ActionPerformed

    private void rbnQ105ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnQ105ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnQ105ActionPerformed

    private void rbnQ106ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnQ106ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnQ106ActionPerformed

    private void rbnQ107ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnQ107ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnQ107ActionPerformed

    private void rbnQ108ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnQ108ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnQ108ActionPerformed

    private void rbnQ109ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnQ109ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnQ109ActionPerformed

    private void rbnQ110ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnQ110ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnQ110ActionPerformed

    private void rbnQ111ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnQ111ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnQ111ActionPerformed

    private void rbnQ112ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnQ112ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnQ112ActionPerformed

    private void rbnQ113ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnQ113ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnQ113ActionPerformed

    private void rbnQ114ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnQ114ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnQ114ActionPerformed

    private void rbnQ115ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnQ115ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnQ115ActionPerformed

    private void rbnQ116ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnQ116ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnQ116ActionPerformed

    private void rbnQ117ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnQ117ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnQ117ActionPerformed

    private void rbnQ118ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnQ118ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnQ118ActionPerformed

    private void rbnQ119ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnQ119ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnQ119ActionPerformed

    private void rbnQ120ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnQ120ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnQ120ActionPerformed

    private void rbnQ121ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnQ121ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnQ121ActionPerformed

    private void rbnQ122ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnQ122ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnQ122ActionPerformed

    private void rbnQ123ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnQ123ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnQ123ActionPerformed

    private void rbnQ124ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnQ124ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnQ124ActionPerformed

    private void rbnQ125ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnQ125ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnQ125ActionPerformed

    private void rbnQ126ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnQ126ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnQ126ActionPerformed

    private void rbnQ127ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnQ127ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnQ127ActionPerformed

    private void rbnQ128ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnQ128ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnQ128ActionPerformed

    private void rbnQ129ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnQ129ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnQ129ActionPerformed

    private void rbnQ130ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnQ130ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnQ130ActionPerformed

    private void rbnQ131ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnQ131ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnQ131ActionPerformed

    private void rbnQ132ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnQ132ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnQ132ActionPerformed

    private void rbnQ133ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnQ133ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnQ133ActionPerformed

    private void rbnQ134ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnQ134ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnQ134ActionPerformed

    private void rbnQ135ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnQ135ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnQ135ActionPerformed

    private void rbnQ136ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnQ136ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnQ136ActionPerformed

    private void rbnQ137ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnQ137ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnQ137ActionPerformed

    private void rbnQ138ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnQ138ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnQ138ActionPerformed

    private void rbnQ139ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnQ139ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnQ139ActionPerformed

    private void rbnQ140ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnQ140ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbnQ140ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int acertos = 0; 

if (rbnQ102.isSelected()) {
    acertos++; 
}
if (rbnQ107.isSelected()) {
    acertos++; 
}
if (rbnQ109.isSelected()) {
    acertos++; 
}
if (rbnQ113.isSelected()) {
    acertos++; 
}
if (rbnQ120.isSelected()) {
    acertos++; 
}
if (rbnQ122.isSelected()) {
    acertos++; 
}
if (rbnQ125.isSelected()) {
    acertos++; 
}
if (rbnQ129.isSelected()) {
    acertos++; 
}
if (rbnQ135.isSelected()) {
    acertos++; 
}
if (rbnQ137.isSelected()) {
    acertos++; 
}
lblResult.setText(""+acertos);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bntGroup1;
    private javax.swing.ButtonGroup bntGroup10;
    private javax.swing.ButtonGroup bntGroup2;
    private javax.swing.ButtonGroup bntGroup3;
    private javax.swing.ButtonGroup bntGroup4;
    private javax.swing.ButtonGroup bntGroup5;
    private javax.swing.ButtonGroup bntGroup6;
    private javax.swing.ButtonGroup bntGroup7;
    private javax.swing.ButtonGroup bntGroup8;
    private javax.swing.ButtonGroup bntGroup9;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel lblQ1;
    private javax.swing.JLabel lblQ10;
    private javax.swing.JLabel lblQ11;
    private javax.swing.JLabel lblQ2;
    private javax.swing.JLabel lblQ3;
    private javax.swing.JLabel lblQ4;
    private javax.swing.JLabel lblQ5;
    private javax.swing.JLabel lblQ6;
    private javax.swing.JLabel lblQ7;
    private javax.swing.JLabel lblQ8;
    private javax.swing.JLabel lblQ9;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblTitle01;
    private javax.swing.JLabel lblTitle02;
    private javax.swing.JLabel lblTitle10;
    private javax.swing.JLabel lblTitle3;
    private javax.swing.JLabel lblTitle4;
    private javax.swing.JLabel lblTitle5;
    private javax.swing.JLabel lblTitle6;
    private javax.swing.JLabel lblTitle7;
    private javax.swing.JLabel lblTitle8;
    private javax.swing.JLabel lblTitle9;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlQ1;
    private javax.swing.JPanel pnlQ10;
    private javax.swing.JPanel pnlQ2;
    private javax.swing.JPanel pnlQ3;
    private javax.swing.JPanel pnlQ4;
    private javax.swing.JPanel pnlQ5;
    private javax.swing.JPanel pnlQ6;
    private javax.swing.JPanel pnlQ7;
    private javax.swing.JPanel pnlQ8;
    private javax.swing.JPanel pnlQ9;
    private javax.swing.JPanel pnlResultado;
    private javax.swing.JPanel pnlWelcome;
    private javax.swing.JRadioButton rbnQ101;
    private javax.swing.JRadioButton rbnQ102;
    private javax.swing.JRadioButton rbnQ103;
    private javax.swing.JRadioButton rbnQ104;
    private javax.swing.JRadioButton rbnQ105;
    private javax.swing.JRadioButton rbnQ106;
    private javax.swing.JRadioButton rbnQ107;
    private javax.swing.JRadioButton rbnQ108;
    private javax.swing.JRadioButton rbnQ109;
    private javax.swing.JRadioButton rbnQ110;
    private javax.swing.JRadioButton rbnQ111;
    private javax.swing.JRadioButton rbnQ112;
    private javax.swing.JRadioButton rbnQ113;
    private javax.swing.JRadioButton rbnQ114;
    private javax.swing.JRadioButton rbnQ115;
    private javax.swing.JRadioButton rbnQ116;
    private javax.swing.JRadioButton rbnQ117;
    private javax.swing.JRadioButton rbnQ118;
    private javax.swing.JRadioButton rbnQ119;
    private javax.swing.JRadioButton rbnQ120;
    private javax.swing.JRadioButton rbnQ121;
    private javax.swing.JRadioButton rbnQ122;
    private javax.swing.JRadioButton rbnQ123;
    private javax.swing.JRadioButton rbnQ124;
    private javax.swing.JRadioButton rbnQ125;
    private javax.swing.JRadioButton rbnQ126;
    private javax.swing.JRadioButton rbnQ127;
    private javax.swing.JRadioButton rbnQ128;
    private javax.swing.JRadioButton rbnQ129;
    private javax.swing.JRadioButton rbnQ130;
    private javax.swing.JRadioButton rbnQ131;
    private javax.swing.JRadioButton rbnQ132;
    private javax.swing.JRadioButton rbnQ133;
    private javax.swing.JRadioButton rbnQ134;
    private javax.swing.JRadioButton rbnQ135;
    private javax.swing.JRadioButton rbnQ136;
    private javax.swing.JRadioButton rbnQ137;
    private javax.swing.JRadioButton rbnQ138;
    private javax.swing.JRadioButton rbnQ139;
    private javax.swing.JRadioButton rbnQ140;
    private javax.swing.JTextArea txtQ02;
    private javax.swing.JTextArea txtQ1;
    private javax.swing.JTextArea txtQ10;
    private javax.swing.JTextArea txtQ3;
    private javax.swing.JTextArea txtQ4;
    private javax.swing.JTextArea txtQ5;
    private javax.swing.JTextArea txtQ6;
    private javax.swing.JTextArea txtQ7;
    private javax.swing.JTextArea txtQ8;
    private javax.swing.JTextArea txtQ9;
    // End of variables declaration//GEN-END:variables
}
